<a href="https://colab.research.google.com/github/senasung37/recommendation/blob/main/movie_recommender_surprise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

코드출처: 이수안 컴퓨터 연구소 <br>
- 링크: https://www.youtube.com/watch?v=6TP51jvjLsE&t=698s

#라이브러리 & 데이터 불러오기

surprise: 추천 시스템 개발을 위한 라이브러리 

In [1]:
#surprise 라이브러리 설치
!pip install scikit-surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 11.8 MB 4.3 MB/s 
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.1-cp37-cp37m-linux_x86_64.whl size=1633965 sha256=b52898b12728bbbcc4d28b14a3f7e9ec2820858c09ded36d15d9ce7b014bb1d3
  Stored in directory: /root/.cache/pip/wheels/76/44/74/b498c42be47b2406bd27994e16c5188e337c657025ab400c1c
Successfully built scikit-surprise


In [2]:
#라이브러리 불러오기
from surprise import SVD
from surprise import Dataset
from surprise.model_selection import cross_validate

In [3]:
#데이터 불러오기 (ml-100k: 데이터 종류)
#피쳐: 사용자id, 영화id, 평점, 시간)
data = Dataset.load_builtin('ml-100k', prompt=False)
data.raw_ratings[:10]

Trying to download dataset from http://files.grouplens.org/datasets/movielens/ml-100k.zip...
Done! Dataset ml-100k has been saved to /root/.surprise_data/ml-100k


[('196', '242', 3.0, '881250949'),
 ('186', '302', 3.0, '891717742'),
 ('22', '377', 1.0, '878887116'),
 ('244', '51', 2.0, '880606923'),
 ('166', '346', 1.0, '886397596'),
 ('298', '474', 4.0, '884182806'),
 ('115', '265', 2.0, '881171488'),
 ('253', '465', 5.0, '891628467'),
 ('305', '451', 3.0, '886324817'),
 ('6', '86', 3.0, '883603013')]

In [4]:
#모델 설정(SVD - matrix factorization 알고리즘, 비어있는 값들 예측)
model = SVD()

In [5]:
#모델 검증
cross_validate(model, data, measures=['rmse', 'mae'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9346  0.9343  0.9381  0.9454  0.9251  0.9355  0.0066  
MAE (testset)     0.7367  0.7366  0.7398  0.7450  0.7322  0.7381  0.0042  
Fit time          6.88    4.88    4.83    4.89    4.89    5.27    0.81    
Test time         0.29    0.15    0.19    0.20    0.14    0.20    0.05    


{'fit_time': (6.884903192520142,
  4.876851558685303,
  4.826300859451294,
  4.894756078720093,
  4.886202096939087),
 'test_mae': array([0.7366974 , 0.73663943, 0.73981255, 0.74499876, 0.73215277]),
 'test_rmse': array([0.93463039, 0.93432728, 0.93811037, 0.9453884 , 0.9251129 ]),
 'test_time': (0.2941012382507324,
  0.1516094207763672,
  0.19150424003601074,
  0.1983647346496582,
  0.1437373161315918)}

#컨텐츠 기반 필터링
사용자가 좋아하는 상품과 유사한 상품 추천(예시: 나와 비슷한 취향의 사용자가 시청한 영화 추천)
- 장점: 많은 수의 사용자 대상으로 쉽게 확장, 관심 없던 상품 추천 가능
- 단점: 입력 특성을 직접 설계해야 돼서 도메인 지식 필요, 사용자 기존 관심사항 기반으로만 추천 가능

In [6]:
import numpy as np
from surprise import Dataset

In [16]:
#데이터 array로 만들기
raw_data = np.array(data.raw_ratings, dtype=int)
raw_data

array([[      196,       242,         3, 881250949],
       [      186,       302,         3, 891717742],
       [       22,       377,         1, 878887116],
       ...,
       [      276,      1090,         1, 874795795],
       [       13,       225,         2, 882399156],
       [       12,       203,         3, 879959583]])

In [19]:
#userid, movieid가 0부터 시작하도록 변경
raw_data[:,0] -= 1
raw_data[:,1] -= 1
raw_data


array([[      195,       241,         3, 881250949],
       [      185,       301,         3, 891717742],
       [       21,       376,         1, 878887116],
       ...,
       [      275,      1089,         1, 874795795],
       [       12,       224,         2, 882399156],
       [       11,       202,         3, 879959583]])

In [9]:
#유저, 영화 최대값으로 shape 만들기
n_users = np.max(raw_data[:, 0])
n_movies = np.max(raw_data[:, 1])
shape = (n_users + 1, n_movies + 1)
shape

(943, 1682)

In [48]:
#user x movie 인접행렬 만들기(데이터가 있으면 1, 없으면 0)
adj_matrix = np.ndarray(shape, dtype=int)
for user_id, movie_id, rating, time in raw_data:
  adj_matrix[user_id, movie_id] = 1.
adj_matrix

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [50]:
#유사도 평가 알고리즘 - 입력한 id와 가장 유사한 similarity 및 ID 도출
my_id = int(input())
my_vector = adj_matrix[my_id]
best_match, best_match_id, best_match_vector = -1, -1, []

for user_id, user_vector in enumerate(adj_matrix):
  if my_id != user_id:
    similarity = np.dot(my_vector, user_vector)
    if similarity > best_match:
      best_match = similarity
      best_match_id = user_id
      best_match_vector = user_vector
print("Best Match: {}, Best Match ID: {}".format(best_match, best_match_id))

0
Best Match: 183, Best Match ID: 275
